CREATE TABLE PIZZA_SALES (
	PIZZA_ID INTEGER PRIMARY KEY,
	ORDER_ID INTEGER,
	PIZZA_NAME_ID TEXT,
	QUANTITY INTEGER,
	ORDER_DATE DATE,
	ORDER_TIME TIME,
	UNIT_PRICE NUMERIC(10, 2),
	TOTAL_PRICE NUMERIC(10, 2),
	PIZZA_SIZE VARCHAR(10),
	PIZZA_CATEGORY VARCHAR(50),
	PIZZA_INGREDIENTS TEXT,
	PIZZA_NAME TEXT
);

SELECT
	*
FROM
	PIZZA_SALES;

-- 1) Find out Pizza sales Total Revenue.
SELECT
	SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM
	PIZZA_SALES;

-- 2) Find out Total orders.
SELECT
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM
	PIZZA_SALES;

-- 3) Average Order value.
SELECT
	CAST(
		CAST(SUM(TOTAL_PRICE) AS DECIMAL(10, 2)) / CAST(COUNT(DISTINCT ORDER_ID) AS DECIMAL(10, 2)) AS DECIMAL(10, 2)
	) AS AVG_ORDER_VALUE
FROM
	PIZZA_SALES;

-- 4) Total Pizzas Sold.
SELECT
	SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM
	PIZZA_SALES;

-- 5) Average Pizzas Per Order.
SELECT
	SUM(QUANTITY) / COUNT(DISTINCT ORDER_ID) AS AVG_PIZZA_PER_ORDER
FROM
	PIZZA_SALES;

SELECT
	*
FROM
	PIZZA_SALES;

-- Analysis
-- 1) Monthly Trend for total Revenue.
SELECT
	TO_CHAR(ORDER_DATE, 'MONTH') AS MONTH,
	SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM
	PIZZA_SALES
GROUP BY
	TO_CHAR(ORDER_DATE, 'MONTH');

-- 2) Daily Trand for Total Orders.
SELECT
	TO_CHAR(ORDER_DATE, 'DAY') AS DAY,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDER
FROM
	PIZZA_SALES
GROUP BY
	TO_CHAR(ORDER_DATE, 'DAY');

-- 3) Percentage of Sales by Pizza Category.
SELECT
	PIZZA_CATEGORY,
	SUM(TOTAL_PRICE) AS TOTAL_REVENUE,
	CAST(
		SUM(TOTAL_PRICE) * 100 / (
			SELECT
				SUM(TOTAL_PRICE)
			FROM
				PIZZA_SALES
		) AS DECIMAL(10, 2)
	) AS PCT
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_CATEGORY;

-- 4) Percentage of Sales by Pizza Size.
SELECT
	PIZZA_SIZE,
	SUM(TOTAL_PRICE) AS TOTAL_REVENUE,
	CAST(
		SUM(TOTAL_PRICE) * 100 / (
			SELECT
				SUM(TOTAL_PRICE)
			FROM
				PIZZA_SALES
		) AS DECIMAL(10, 2)
	) AS PCT
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_SIZE;

-- 5) Total Pizza sold by pizza size and category.
SELECT
	PIZZA_SIZE,
	SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_SIZE;

SELECT
	PIZZA_CATEGORY,
	SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_CATEGORY;

-- 6) Revenue by Pizza Name.
SELECT
	PIZZA_NAME,
	SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_NAME
ORDER BY
	TOTAL_REVENUE DESC
LIMIT
	5;

-- 7. Bottom 5 Pizzas by Revenue
SELECT
	PIZZA_NAME,
	SUM(TOTAL_PRICE) AS TOTAL_REVENUE
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_NAME
ORDER BY
	TOTAL_REVENUE ASC
LIMIT
	5;

-- 8. Top 5 Pizzas by Quantity
SELECT
	PIZZA_NAME,
	SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_NAME
ORDER BY
	TOTAL_PIZZA_SOLD DESC
LIMIT
	5;

-- 9. Bottom 5 Pizzas by Quantity
SELECT
	PIZZA_NAME,
	SUM(QUANTITY) AS TOTAL_PIZZA_SOLD
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_NAME
ORDER BY
	TOTAL_PIZZA_SOLD ASC
LIMIT
	5;

-- 10. Top 5 Pizzas by Total Orders
SELECT
	PIZZA_NAME,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_NAME
ORDER BY
	TOTAL_ORDERS DESC
LIMIT
	5;

-- 11. Bottom 5 Pizzas by Total Orders
SELECT
	PIZZA_NAME,
	COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS
FROM
	PIZZA_SALES
GROUP BY
	PIZZA_NAME
ORDER BY
	TOTAL_ORDERS ASC
LIMIT
	5;